ai_content_generation.settings:
  type: config_object
  label: 'AI Content Generation Settings'
  mapping:
    model:
      type: string
      label: 'The AI model to use'
    role:
      type: string
      label: 'The role to use for the AI'
    prompt:
      type: string
      label: 'The prompt to use for the AI'
